alias: get-tool-perf
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML frameworks
clean_files: []
new_env_keys:
- MLC_PERF_BIN_WITH_PATH
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,generic-sys-util,_linux-tools
tags:
- tool
- perf
- get
- perf-tool
uid: 0f6f05ea6fc54b9d
