alias: get-wkhtmltopdf
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- wkhtmltopdf
deps:
  - tags: detect,os
  - tags: detect,sudo
    skip_if_env:
      MLC_HOST_OS_TYPE:
        - windows
  - tags: get,generic-sys-util,_wkhtmltopdf
    enable_if_env:
      MLC_HOST_OS_TYPE:
        - darwin
uid: 67ec874a3dfe4b87
docker:
  pre_run_cmds:
    - mlc pull repo
variations:
  with-qt:
    group: qt
    default: true