rem connect CM portable scripts with CK env

set MLC_ML_TORCH_MODEL_NAME=resnet50
set MLC_ML_MODEL_INPUT_DATA_TYPE=float32
set MLC_ML_MODEL_IMAGE_HEIGHT=224
set MLC_ML_MODEL_IMAGE_WIDTH=224

rem set MLC_DATASET_IMAGENET_PREPROCESSED_DIR=%MLC_DATASET_PREPROCESSED_PATH%

set MLC_DATASET_IMAGENET_PREPROCESSED_DIR=%MLC_DATASET_PREPROCESSED_FULL_PATH%
set MLC_CAFFE_IMAGENET_SYNSET_WORDS_TXT=%MLC_DATASET_AUX_PATH%\synset_words.txt
set MLC_DATASET_IMAGENET_PREPROCESSED_DATA_TYPE=float32
set MLC_RESULTS_DIR=%MLC_TMP_CURRENT_SCRIPT_PATH%\results
set ML_MODEL_DATA_LAYOUT=NCHW

%MLC_PYTHON_BIN_WITH_PATH% -m pip install -r %MLC_TMP_CURRENT_SCRIPT_PATH%\requirements.txt
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

%MLC_PYTHON_BIN_WITH_PATH% %MLC_TMP_CURRENT_SCRIPT_PATH%\src\pytorch_classify_preprocessed.py
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
