del /Q %MLC_JAVA_PREBUILT_FILENAME%.zip

wget --no-check-certificate %MLC_JAVA_PREBUILT_URL%%MLC_JAVA_PREBUILT_FILENAME%.zip
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

unzip %MLC_JAVA_PREBUILT_FILENAME%.zip
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

del /Q %MLC_JAVA_PREBUILT_FILENAME%.zip
