alias: get-one-api
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
default_version: 2025.3.1
deps:
- tags: detect,os
name: Detect or install OneAPI compiler
new_env_keys:
- MLC_ONEAPI_*
- MLC_ONEAPI_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- +PATH
- +LD_LIBRARY_PATH

input_mapping:
  oneapi_dir: MLC_ONEAPI_DIR_PATH
  clean: MLC_ONEAPI_CLEAN_INSTALL
 
post_deps_off:
- tags: get,compiler-flags
sort: 500
tags:
- get
- oneapi
- compiler
- get-oneapi
uid: 1af872e81ef54742

tests:
  run_inputs:
    - variations_list:
      - fortran

versions:
  2025.3.1:
    env:
      MLC_ONEAPI_INSTALL_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/d640da34-77cc-4ab2-8019-ac5592f4ec19
      MLC_ONEAPI_INSTALL_FILENAME: intel-oneapi-base-toolkit-2025.3.0.375_offline.sh
      MLC_ONEAPI_CXX_COMPILER_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/5adfc398-db78-488c-b98f-78461b3c5760
      MLC_ONEAPI_CXX_COMPILER_FILENAME: intel-dpcpp-cpp-compiler-2025.3.1.16_offline.sh
      MLC_ONEAPI_FORTRAN_COMPILER_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/724303ca-6927-4327-a560-e0aabb55b010
      MLC_ONEAPI_FORTRAN_COMPILER_FILENAME: intel-fortran-compiler-2025.3.1.16_offline.sh
      MLC_ONEAPI_INSTALL_VERSION_PREFIX: '2025.3'
      MLC_VERSION: '2025.3.1'
      MLC_ONEAPI_CXX: 'yes'
  2025.2.1:
    env:
      MLC_ONEAPI_INSTALL_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3b7a16b3-a7b0-460f-be16-de0d64fa6b1e
      MLC_ONEAPI_INSTALL_FILENAME: intel-oneapi-base-toolkit-2025.2.1.44_offline.sh
      MLC_ONEAPI_FORTRAN_COMPILER_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/a31a1a8e-4b6f-4548-a554-fe3ac1c8b230
      MLC_ONEAPI_FORTRAN_COMPILER_FILENAME: intel-fortran-essentials-2025.2.1.5_offline.sh
      MLC_ONEAPI_INSTALL_VERSION_PREFIX: '2025.2'
      MLC_VERSION: '2025.2.1'

  2025.2.0:
    env:
      MLC_ONEAPI_INSTALL_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/bd1d0273-a931-4f7e-ab76-6a2a67d646c7
      MLC_ONEAPI_INSTALL_FILENAME: intel-oneapi-base-toolkit-2025.2.0.592.sh
      MLC_ONEAPI_INSTALL_VERSION_PREFIX: '2025.2'
      MLC_VERSION: '2025.2.0'

  2025.1.0:
    env:
      MLC_ONEAPI_INSTALL_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/6bfca885-4156-491e-849b-1cd7da9cc760
      MLC_ONEAPI_INSTALL_FILENAME: intel-oneapi-base-toolkit-2025.1.1.36_offline.sh
      MLC_ONEAPI_FORTRAN_COMPILER_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2238465b-cfc7-4bf8-ad04-e55cb6577cba
      MLC_ONEAPI_FORTRAN_COMPILER_FILENAME: intel-fortran-essentials-2025.1.1.8_offline.sh
      MLC_ONEAPI_INSTALL_VERSION_PREFIX: '2025.1'
      MLC_VERSION: '2025.1.1'
      
variations:
  path.#:
    env:
      MLC_ONEAPI_DIR_PATH: "#"
  fortran:
    env:
      MLC_ONEAPI_FORTRAN: 'yes'
