echo.

del /Q /S %MLC_ARIA2_DOWNLOAD_FILE%

wget --no-check-certificate %MLC_ARIA2_DOWNLOAD_URL%
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

unzip -o -q %MLC_ARIA2_DOWNLOAD_FILE%
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
