echo.

if NOT "%MLC_GENERIC_PYTHON_PIP_URL%" == "" (

  "%MLC_PYTHON_BIN_WITH_PATH%" -m pip install %MLC_GENERIC_PYTHON_PIP_URL% %MLC_GENERIC_PYTHON_PIP_EXTRA%
  IF %ERRORLEVEL% NEQ 0 EXIT 1

) else (

  "%MLC_PYTHON_BIN_WITH_PATH%" -m pip install %MLC_GENERIC_PYTHON_PACKAGE_NAME%%MLC_TMP_PIP_VERSION_STRING% %MLC_GENERIC_PYTHON_PIP_EXTRA%
  IF %ERRORLEVEL% NEQ 0 EXIT 1

)


