export PATH=${MLC_CONDA_BIN_PATH}:$PATH

export CALIBRATION_ANNOTATIONS=${MLC_DATASET_CALIBRATION_ANNOTATIONS_FILE_PATH}

export CALIBRATION_DATA_DIR=${MLC_CALIBRATION_DATASET_PATH}
export MODEL_CHECKPOINT=${MLC_ML_MODEL_FILE_WITH_PATH}

cd ${MLC_HARNESS_CODE_ROOT}

bash run_calibration.sh
test "$?" -eq 0 || exit "$?"
