alias: get-git-repo
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
cache_expiration: 5d
category: DevOps automation
default_env:
  MLC_GIT_CHECKOUT_FOLDER: repo
  MLC_GIT_DEPTH: --depth 4
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ' --recurse-submodules'
  MLC_GIT_URL: https://github.com/mlcommons/mlperf-automations
deps:
- tags: detect,os
input_mapping:
  branch: MLC_GIT_CHECKOUT
  depth: MLC_GIT_DEPTH
  env_key: MLC_GIT_ENV_KEY
  folder: MLC_GIT_CHECKOUT_FOLDER
  patch: MLC_GIT_PATCH
  pull: MLC_GIT_REPO_PULL
  submodules: MLC_GIT_RECURSE_SUBMODULES
  update: MLC_GIT_REPO_PULL
new_env_keys:
- MLC_GIT_CHECKOUT_PATH
- MLC_GIT_REPO_*
- <<<MLC_GIT_CHECKOUT_PATH_ENV_NAME>>>
post_deps:
- dynamic: true
  enable_if_env:
    MLC_GIT_REPO_PULL:
    - 'yes'
    - 'True'
  force_env_keys:
  - MLC_GIT_CHECKOUT_PATH
  names:
  - pull-git-repo
  tags: pull,git,repo
print_env_at_the_end:
  MLC_GIT_CHECKOUT_PATH: MLC cache path to the Git repo
tags:
- get
- git
- repo
- repository
- clone
uid: ed603e7292974f10
variations:
  branch.#:
    env:
      MLC_GIT_BRANCH: '#'
    group: checkout
  cherrypicks.#:
    env:
      MLC_GIT_CHERRYPICKS: '#'
  full-history:
    env:
      MLC_GIT_DEPTH: ''
    group: git-history
  lfs:
    deps:
    - tags: get,generic,sys-util,_git-lfs
    env:
      MLC_GIT_REPO_NEEDS_LFS: 'yes'
  no-recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ''
  patch:
    env:
      MLC_GIT_PATCH: 'yes'
  patch.#:
    env:
      MLC_GIT_PATCH: 'yes'
      +,MLC_GIT_PATCH_FILEPATHS:
      - '#'
  pr-to-apply.#:
    env:
      MLC_GIT_PR_TO_APPLY: '#'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  sha.#:
    cache_expiration: 500d
    default_variations:
      git-history: full-history
    env:
      MLC_GIT_SHA: '#'
    group: post-checkout
  short-history:
    default: true
    env:
      MLC_GIT_DEPTH: --depth 5
    group: git-history
  submodules.#:
    env:
      MLC_GIT_SUBMODULES: '#'
  tag.#:
    cache_expiration: 500d
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: checkout
