alias: get-rclone-config
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false #keeping cache off as rerunning the command is safe
can_force_cache: true
tags:
- get
- rclone-config
uid: 6c59ddbc6cd046e3
variations:
  mlc-inference:
    env:
      MLC_RCLONE_CONFIG_CMD: 'rclone config create mlc-inference s3 provider=Cloudflare access_key_id=f65ba5eef400db161ea49967de89f47b secret_access_key=fbea333914c292b854f14d3fe232bad6c5407bf0ab1bebf78833c2b359bdfd2b endpoint=https://c2686074cb2caf5cbaf6d134bdba8b47.r2.cloudflarestorage.com'
  mlperf-llama2:
    env:
      MLC_RCLONE_CONFIG_CMD: 'rclone config create mlc-llama2 drive config_is_local=false scope=drive.readonly root_folder_id=11tBZvvrh0FCm3XuR5E849K42TqftYdUF'
      MLC_RCLONE_CONNECT_CMD: 'rclone config reconnect mlc-llama2:'
  mlperf-llama3-1:
    env:
      MLC_RCLONE_CONFIG_CMD: 'rclone config create mlc-llama3-1 drive config_is_local=false scope=drive.readonly root_folder_id=12K-2yvmr1ZSZ7SLrhidCbWc0BriN98am'
      MLC_RCLONE_CONNECT_CMD: 'rclone config reconnect mlc-llama3-1:'
  waymo:
    env:
      MLC_RCLONE_CONFIG_CMD: 'rclone config create mlc-waymo drive config_is_local=false scope=drive.readonly root_folder_id=1xbfnaUurFeXliFFl1i1gj48eRU2NDiH5'
      MLC_RCLONE_CONNECT_CMD: 'rclone config reconnect mlc-waymo:'
