alias: get-lib-jemalloc
automation_alias: script
automation_uid: 5b4e0237da074764
category: Detection or installation of tools and artifacts
cache: true
deps:
  - tags: get,git,repo
    env:
      MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_JEMALLOC_SRC_PATH
    force_env_keys:
      - MLC_GIT_*
    update_tags_from_env_with_prefix:
      _branch.:
        - MLC_GIT_CHECKOUT
      _repo.:
        - MLC_GIT_URL
      _sha.:
        - MLC_GIT_SHA
      _submodules.:
        - MLC_GIT_SUBMODULES
    names:
      - jemalloc-repo
    extra_cache_tags: jemalloc,repo,jemalloc-repo
  - tags: get,generic-sys-util,_autoconf
  - tags: get,generic-sys-util,_build-essential
    env:
      MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: on
new_env_keys:
  - MLC_JEMALLOC_PATH
  - MLC_JEMALLOC_LIB_PATH
  - +LD_LIBRARY_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- lib
- lib-jemalloc
- jemalloc
tests:
  run_inputs:
  - variations_list:
    - branch.dev,lg-page.21,lg-quantum.3
  - variations_list:
    - config.'--with-lg-page=21 --with-lg-quantum=3'
   
uid: 406439a446e04fb7
variations:
  version.official:
    base:
      - url.official
  url.#:
    group: version
    env:
      MLC_GIT_URL: '#'
  url.official:
    group: version
    default: true
    env:
      MLC_GIT_URL: https://github.com/jemalloc/jemalloc.git
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  sha.#:
    env:
      MLC_GIT_SHA: '#'
  config.#:
    env:
      MLC_JEMALLOC_CONFIG: '#'
  enable-stats:
    env:
      MLC_JEMALLOC_STATS: true
  enable-prof:
    env:
      MLC_JEMALLOC_PROF: true
  lg-page.#:
    env:
      MLC_JEMALLOC_LG_PAGE: '#'
  lg-hugepage.#:
    env:
      MLC_JEMALLOC_LG_PAGE: '#'
  lg-quantum.#:
    env:
      MLC_JEMALLOC_LG_QUANTUM: '#'

