alias: build-dockerfile
uid: e66a7483230d4641

automation_alias: script
automation_uid: 5b4e0237da074764

tags:
- build
- dockerfile

cache: false

category: Docker automation

default_env:
  MLC_DOCKER_BUILD_SLIM: 'no'
  MLC_DOCKER_IMAGE_EOL: '

    '
  MLC_DOCKER_OS: ubuntu
  MLC_DOCKER_NOT_PULL_UPDATE: False
  MLC_MLOPS_REPO_BRANCH: dev

input_mapping:
  build: MLC_BUILD_DOCKER_IMAGE
  cache: MLC_DOCKER_CACHE
  mlc_repo: MLC_MLOPS_REPO
  mlc_repo_flags: MLC_DOCKER_ADD_FLAG_TO_MLC_MLOPS_REPO
  mlc_repos: MLC_DOCKER_EXTRA_MLC_REPOS
  mlc_repo_branch: MLC_MLOPS_REPO_BRANCH
  comments: MLC_DOCKER_RUN_COMMENTS
  copy_files: MLC_DOCKER_COPY_FILES
  base_image: MLC_DOCKER_IMAGE_BASE
  os: MLC_DOCKER_OS
  os_version: MLC_DOCKER_OS_VERSION
  docker_base_image: MLC_DOCKER_IMAGE_BASE
  docker_os: MLC_DOCKER_OS
  docker_os_version: MLC_DOCKER_OS_VERSION
  dockerfile_env: MLC_DOCKERFILE_ENV
  dockerfile_build_env: MLC_DOCKERFILE_BUILD_ENV
  extra_sys_deps: MLC_DOCKER_EXTRA_SYS_DEPS
  fake_docker_deps: MLC_DOCKER_FAKE_DEPS
  fake_run_option: MLC_DOCKER_FAKE_RUN_OPTION
  file_path: MLC_DOCKERFILE_WITH_PATH
  gh_token: MLC_GH_TOKEN
  image_repo: MLC_DOCKER_IMAGE_REPO
  image_tag: MLC_DOCKER_IMAGE_TAG
  mlc_repo_path: MLC_REPO_PATH
  package_manager_update_cmd: MLC_PACKAGE_MANAGER_UPDATE_CMD
  pip_extra_flags: MLC_DOCKER_PIP_INSTALL_EXTRA_FLAGS
  post_file: DOCKER_IMAGE_POST_FILE
  post_run_cmds: MLC_DOCKER_POST_RUN_COMMANDS
  pre_run_cmds: MLC_DOCKER_PRE_RUN_COMMANDS
  real_run: MLC_REAL_RUN
  run_cmd: MLC_DOCKER_RUN_CMD
  run_cmd_extra: MLC_DOCKER_RUN_CMD_EXTRA
  script_tags: MLC_DOCKER_RUN_SCRIPT_TAGS
  skip_mlc_sys_upgrade: MLC_DOCKER_SKIP_MLC_SYS_UPGRADE
  push_image: MLC_DOCKER_PUSH_IMAGE
  docker_not_pull_update: MLC_DOCKER_NOT_PULL_UPDATE
  user: MLC_DOCKER_USER

new_env_keys:
- MLC_DOCKERFILE_*

deps:
  - tags: get,docker
    names:
    - docker

post_deps:
- enable_if_env:
    MLC_BUILD_DOCKER_IMAGE:
    - 'yes'
  names:
  - build-docker-image
  tags: build,docker,image

variations:
  slim:
    env:
      MLC_DOCKER_BUILD_SLIM: 'yes'
