alias: detect-cpu
automation_alias: script
automation_uid: 5b4e0237da074764
category: Platform information
cache: true
cache_expiration: 1h
clean_files:
- tmp-lscpu.out
- tmp-systeminfo.csv
- tmp-wmic-cpu.csv
deps:
- tags: detect,os
  names:
    - detect-os
new_env_keys:
- MLC_HOST_CPU_*
- MLC_HOST_MEMORY_CAPACITY
- MLC_HOST_DISK_CAPACITY
new_state_keys:
- host_device_raw_info
tags:
- detect
- cpu
- detect-cpu
- info
uid: 586c8a43320142f7
