if exist %MLC_DOCKERFILE_WITH_PATH% (
rem  echo .git > .dockerignore

rem  echo.
rem  echo docker build %MLC_DOCKER_CACHE_ARG%  %MLC_DOCKER_BUILD_ARGS% -f %MLC_DOCKERFILE_WITH_PATH% -t %MLC_DOCKER_IMAGE_REPO%/%MLC_DOCKER_IMAGE_NAME%:%MLC_DOCKER_IMAGE_TAG% .

rem  echo.
rem  docker build %MLC_DOCKER_CACHE_ARG%  %MLC_DOCKER_BUILD_ARGS% -f "%MLC_DOCKERFILE_WITH_PATH%" -t "%MLC_DOCKER_IMAGE_REPO%/%MLC_DOCKER_IMAGE_NAME%:%MLC_DOCKER_IMAGE_TAG%" .

  %MLC_DOCKER_BUILD_CMD%
  IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

  echo.
)
