echo %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH%

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% --version > tmp-ver.out
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

more tmp-ver.out

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% --licenses
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% ^
    "tools" ^
    "platform-tools" ^
    "extras;android;m2repository" ^
    "extras;google;m2repository" ^
    "extras;google;google_play_services" ^
    "build-tools;%MLC_ANDROID_BUILD_TOOLS_VERSION%"
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% "platforms;android-%MLC_ANDROID_VERSION%"
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% "cmake;%MLC_ANDROID_CMAKE_VERSION%"
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

call %MLC_ANDROID_SDK_MANAGER_BIN_WITH_PATH% "ndk;%MLC_ANDROID_NDK_VERSION%"
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
