alias: get-mlperf-inference-results
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT: master
  MLC_GIT_DEPTH: --depth 1
  MLC_GIT_PATCH: 'no'
deps: []
new_env_keys:
- MLC_MLPERF_INFERENCE_RESULTS_*
prehook_deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MLPERF_INFERENCE_RESULTS_PATH
  extra_cache_tags: mlperf,inference,results,official
  force_env_keys:
  - MLC_GIT_*
  names:
  - inference-results-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _repo.:
    - MLC_GIT_URL
tags:
- get
- results
- inference
- official
- inference-results
- mlcommons
- mlperf
uid: 36bae5b25dbe41da
variations:
  code-only:
    adr:
      inference-results-repo:
        tags: _branch.mlc-code-only
    group: repo-branch
  code-only-for-v5.0:
    adr:
      inference-results-repo:
        tags: _branch.mlc-code-only-for-v5.0
    group: repo-branch
  ctuning:
    env:
      GITHUB_REPO_OWNER: ctuning
    group: source-repo
  custom:
    env:
      GITHUB_REPO_OWNER: arjunsuresh
    group: source-repo
  go:
    env:
      GITHUB_REPO_OWNER: GATEOverflow
    group: source-repo
  mlcommons:
    default: true
    env:
      GITHUB_REPO_OWNER: mlcommons
    group: source-repo
  nvidia-only:
    env:
      GITHUB_REPO_OWNER: GATEOverflow
      NVIDIA_ONLY: 'yes'
    group: source-repo
  v5.0:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v5.0.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v5.0
      MLC_VERSION: "v5.0"
versions:
  v2.1:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v2.1.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v2.1
  v3.0:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v3.0.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v3.0
  v3.1:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v3.1.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v3.1
  v4.0:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v4.0.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v4.0
  v4.1:
    env:
      MLC_GIT_URL: https://github.com/<<<GITHUB_REPO_OWNER>>>/inference_results_v4.1.git
      MLC_MLPERF_INFERENCE_RESULTS_VERSION_NAME: v4.1

