alias: install-llvm-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- skip_if_env:
    MLC_LLVM_CONDA_ENV:
    - 'yes'
  tags: get,cmake
- skip_if_env:
    MLC_LLVM_CONDA_ENV:
    - 'yes'
  tags: get,generic-sys-util,_ninja-build
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_LLVM_SRC_REPO_PATH
  extra_cache_tags: llvm,src,llvm-src,llvm-src-repo
  force_env_keys:
  - MLC_GIT_*
  names:
  - llvm-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
    _tag.llvmorg-:
    - MLC_VERSION
env:
  MLC_GIT_URL: https://github.com/llvm/llvm-project
name: Build LLVM compiler from sources (can take >30 min)
new_env_keys:
- MLC_LLVM_*
- MLC_GET_DEPENDENT_CACHED_PATH
- +PATH
- +C_INCLUDE_PATH
post_deps:
- skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,llvm
prehook_deps: []
sort: 1000
tags:
- install
- src
- llvm
- from.src
- src-llvm
uid: 2af16e9a6c5f4702
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  clang:
    default: true
    env:
      +MLC_LLVM_ENABLE_PROJECTS:
        - clang
    group: clang
  lld:
    default: true
    env:
      +MLC_LLVM_ENABLE_PROJECTS:
        - lld
    group: lld
  no-clang:
    group: clang
  no-lld:
    group: lld
  debug:
    env:
      MLC_LLVM_BUILD_TYPE: debug
    group: build-type
  for-intel-mlperf-inference-v3.1-bert:
    adr:
      conda-package:
        tags: _name.bert-pt
    base:
    - tag.llvmorg-15.0.7
    - clang
    - release
    deps:
    - tags: get,gcc
    - names:
      - conda
      tags: get,conda,_name.bert-pt
    - names:
      - conda-package
      - ncurses
      tags: get,conda-package,_package.ncurses,_source.conda-forge
    - names:
      - conda-package
      - ninja
      tags: get,generic,conda-package,_package.ninja
    - names:
      - conda-package
      - cmake
      tags: get,generic,conda-package,_package.cmake
    - tags: get,conda-package,_package.llvm-openmp,_source.conda-forge
    - tags: get,conda-package,_package.chardet
    - names:
      - conda-package
      - libstdcxx-ng
      tags: get,generic,conda-package,_package.libstdcxx-ng,_source.conda-forge
    env:
      MLC_LLVM_CONDA_ENV: 'yes'
  for-intel-mlperf-inference-v3.1-gptj:
    adr:
      conda-package:
        tags: _name.gptj-pt
    base:
    - tag.llvmorg-16.0.6
    - clang
    - release
    deps:
    - tags: get,generic-sys-util,_g++-12
    - tags: get,gcc
      version_min: '12.1'
    - names:
      - conda
      tags: get,conda,_name.gptj-pt
    - names:
      - conda-package
      - python
      tags: get,generic,conda-package,_package.python
      version: '3.9'
    - names:
      - conda-package
      - ncurses
      tags: get,conda-package,_package.ncurses,_source.conda-forge
    - tags: get,conda-package,_package.chardet
    - names:
      - conda-package
      - libstdcxx-ng
      tags: get,generic,conda-package,_package.libstdcxx-ng,_source.conda-forge
    - names:
      - conda-package
      - mkl
      tags: get,generic,conda-package,_package.mkl,_source.intel
      version: 2023.1.0
    - names:
      - conda-package
      - mkl-include
      tags: get,generic,conda-package,_package.mkl-include,_source.intel
      version: 2023.1.0
    - names:
      - conda-package
      - intel-openmp
      tags: get,generic,conda-package,_package.intel-openmp,_source.intel
      version: 2023.1.0
    - names:
      - conda-package
      - gperftools
      tags: get,generic,conda-package,_package.gperftools,_source.conda-forge
    - names:
      - conda-package
      - pybind11
      tags: get,generic,conda-package,_package.pybind11,_source.conda-forge
      version: 2.10.4
    - env:
        + CXXFLAGS:
        - -Wno-nonnull
        - -Wno-maybe-uninitialized
        - -Wno-uninitialized
        - -Wno-free-nonheap-object
        MLC_PYTHON_BIN_WITH_PATH: <<<MLC_CONDA_BIN_PATH>>>/python3
      tags: get,generic-python-lib,_custom-python,_package.torch,_url.git+https://github.com/pytorch/pytorch.git@927dc662386af052018212c7d01309a506fc94cd
    - names:
      - conda-package
      - typing-extensions
      tags: get,generic,conda-package,_package.typing-extensions,_source.conda-forge
    - names:
      - conda-package
      - sympy
      tags: get,generic,conda-package,_package.sympy,_source.conda-forge
    - env:
        MLC_PYTHON_BIN_WITH_PATH: <<<MLC_CONDA_BIN_PATH>>>/python3
      tags: get,generic-python-lib,_custom-python,_package.setuptools
      version_max: 69.9.999
      version_max_usable: 58.2.0
    - env:
        MLC_PYTHON_BIN_WITH_PATH: <<<MLC_CONDA_BIN_PATH>>>/python3
      tags: get,generic-python-lib,_custom-python,_package.neural-compressor,_url.git+https://github.com/intel/neural-compressor.git@a2931eaa4052eec195be3c79a13f7bfa23e54473
    env:
      MLC_LLVM_16_INTEL_MLPERF_INFERENCE: 'yes'
      MLC_LLVM_CONDA_ENV: 'yes'
      CUDA_VISIBLE_DEVICES: ''
      USE_CUDA: '0'
  full-history:
    ad:
      llvm-src-repo:
        tags: _full-history
  release:
    default: true
    env:
      MLC_LLVM_BUILD_TYPE: release
    group: build-type
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  runtimes.#:
    env:
      +MLC_LLVM_ENABLE_RUNTIMES: 
        - '#'
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    base:
    - full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
tests:
  run_inputs:
    - version: "20.1.0"
