alias: get-tool-intel-sde
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLC Utils
deps:
- tags: detect,os
- enable_if_env:
    MLC_DOWNLOAD_URL:
    - true
  extra_cache_tags: intel,sde,tool
  force_cache: true
  skip_if_env:
    MLC_INTEL_SDE_DIR_PATH:
    - true
  tags: download-and-extract,_extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_DOWNLOAD_URL
input_mapping:
  sde_dir: MLC_INTEL_SDE_DIR_PATH
new_env_keys:
- MLC_INTEL_SDE_DIR_PATH
- MLC_INTEL_SDE_BIN_WITH_PATH
- MLC_INTEL_SDE_VERSION
- +PATH
new_state_keys: []
post_deps: []
posthook_deps: []
tags:
- get-intel-sde-tool
tests:
  run_inputs:
  - {}
uid: 3546409e71c847bc
variations:
  version.9_53_0:
    default: true
    env:
      MLC_DOWNLOAD_URL: https://downloadmirror.intel.com/850782/sde-external-9.53.0-2025-03-16-lin.tar.xz
    group: version
