name: Image classification with ONNX

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/test-image-classification-onnx.yml'
      - '**'
      - '!**.md'

jobs:
  mlc-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.10", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure git longpaths (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git config --system core.longpaths true

    - name: Install mlcflow
      run: |
        pip install mlcflow
        pip install tabulate

    - name: Pull MLOps repository
      run: |
        mlc pull repo ${{ github.event.pull_request.head.repo.html_url }} --branch=${{ github.event.pull_request.head.ref }}
    - name: Test image classification with ONNX
      run: |
        mlcr python,app,image-classification,onnx --quiet
